### ISSUE TITLE
HMP2012: posterior fornix samples are incorrectly tagged as oral cavity

### ISSUE THREAD

**Issue by fplaza** [waldronlab/curatedMetagenomicData#153]
Hello,
posterior_fornix samples in the HMP_2012 are incorrectly tagged as 'oralcavity' whereas they should be as 'vagina'.
Could you fix this?

**Comment by edoardopasolli** [comment]
Thanks! Yes we were aware of this. It will be fixed in the next release.

**Comment by schifferl** [comment]
This issue was moved to waldronlab/curatedMetagenomicDataCuration#30

**Comment by lwaldron** [comment]
This issue was fixed in curatedMetagenomicDataCuration long ago (
https://github.com/waldronlab/curatedMetagenomicDataCuration/commit/696ba151ac32fade02991e9a90cd4adaa6ecb200#diff-e0958d8bf3447badde33d65a9959bd7c) and consequently in the pData and man pages here, but the error remains in `combined_metadata` here, so the issue belongs here and not on the curation site.

**Comment by swuyts** [comment]
Hi all,

Any idea when this issue can also be resolver in the `combined_metadata`? I am using that file as the start of my analysis and it would be great if this could be fixed so that I can remove my manual pruning.

Thanks!

**Comment by lwaldron** [comment]
@schifferl do you know why this bug persisted through the April release update? Should I just fix it manually?

**Comment by schifferl** [comment]
Hello all, I am not sure how the bug persisted through the April release update but I will take a look at it today and give you an update. Thanks, Lucas.

**Comment by schifferl** [comment]
@swuyts will you have another look at your analysis and see that you have an updated version of cMD? I have just checked the GitHub and BioC versions (release 1.14.1 and devel 1.15.1) – all `posterior_fornix` samples list their `body_site` as `vagina`. If you find something please let me know, otherwise we are ready to close this issue. (FYI @lwaldron)

**Comment by swuyts** [comment]
Thank you for digging into this.

I had updated all my BioC packages and thought that would do it. But it seems I was still running curatedMetagenomicData `1.12.3` as I am using R `3.5.1`. I therefore needed to update R to `3.6`, reinstall all packages and only then I was able to upgrade to the current version of curatedMetagenomicData.

My apologies, this was completely my fault as the package was not up to date due to an older R version. I think you can indeed close this issue.

Thank you for the great work!
Sander
