### ISSUE TITLE
Update wiki instructions for building cMD3

### ISSUE THREAD

**Issue by hh1985** [waldronlab/curatedMetagenomicData#171]
Hi 

I want to construt an expression set object from our own metaphlan2 and humann2 results so that we can convert it to phyloseq with phylogenetic tree and play all the downstream analysis.  Just wonder if there's any method allowing me to do that?

Thanks,

hh1985

**Comment by lwaldron** [comment]
There is now a new package that should make this easier, but it returns a list of matrices rather than an ExpressionSet: https://github.com/schifferl/curatedmetagenomicdatapipeline

This issue will include testing and documenting this.

**Comment by lwaldron** [comment]
@schifferl I'm adding you just to update the documentation at https://github.com/waldronlab/curatedMetagenomicData/wiki/The-curatedMetagenomicData-pipelines#curatedmetagenomicdata-generating-pipeline when ready.

**Comment by LiNk-NY** [comment]
TreeSummarizedExperiment and mia have converter functions to and from phyloseq https://github.com/FelixErnst/mia/tree/master/R

**Comment by lwaldron** [comment]
If the goal is just to create a phyloseq object, you could also use methods from the [phyloseq package](https://bioconductor.org/packages/phyloseq/). I think you can do what you want now using https://github.com/waldronlab/curatedMetagenomicData/wiki/The-curatedMetagenomicData-pipelines#curatedmetagenomicdata-generating-pipeline, but soon you'll have to use old versions of this repo because we are moving everything to MetaPhlAn3 and HUMAnN3.

**Comment by lwaldron** [comment]
Part of #165

**Comment by schifferl** [comment]
In cMD 3.0.0 this will be covered by a vignette, rather than the wiki. There is an issue (#218) for the "Version Three" vignette, which will provide these instructions. The wiki has been disabled but I've saved the pages. If @hh1985 wants to build cMD 1.X.X style output the instructions are attached, and the "legacy" branch would need to be used. If a phyloseq object was desired in the end, I would start [there](https://github.com/joey711/phyloseq) instead and construct one without going through the effort of making an ExpressionSet. I am closing the issue because it will be resolved by #218 instead, or could be resolved with the other solutions listed here.

[The-curatedMetagenomicData-pipelines.md](https://github.com/waldronlab/curatedMetagenomicData/files/6377574/The-curatedMetagenomicData-pipelines.md)

**Comment by lwaldron** [comment]
Good plan, @schifferl.
