### ISSUE TITLE
Create a GHA to update data/combined_metadata.rda

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#174]
- [ ] copy waldronlab/curatedMetagenomicDataCuration/data/combined_metadata.rda
- [ ] Commit back to package repo in data/ directory
- [ ] run on a CRON job in GHA

**Comment by lwaldron** [comment]
Until the combined_metadata.rda file is available in waldronlab/curatedMetagenomicDataCuration/data/combined_metadata.rda, just copy some random file to data/ to show how it is done. Can add the demo file to package root directory file .Rbuildignore so it's ignored when building curatedMetagenomicData.

**Comment by lwaldron** [comment]
This issue should be closed once it downloads combined_metadata.rda from waldronlab/curatedMetagenomicDataCuration. That repo now has a function to create the R object that goes into combined_metadata.rda, but it needs to be called in that repo's GHA (https://app.zenhub.com/workspace/o/waldronlab/curatedmetagenomicdatacuration/issues/44)

**Comment by jwokaty** [comment]
@lwaldron I want to verify that we want data/combined_metadata.rda in both curatedMetagenomicData and curatedMetagenomicDataCuration repositories. If we are only creating it in curatedMetagenomicDataCuration for curatedMetagenomicData, I can generate combined_metadata.rda via the GHA of curatedMetagenomicData so that we don't have to save it to curatedMetagenomicDataCuration.

**Comment by lwaldron** [comment]
> If we are only creating it in curatedMetagenomicDataCuration for curatedMetagenomicData, I can generate combined_metadata.rda via the GHA of curatedMetagenomicData so that we don't have to save it to curatedMetagenomicDataCuration.

That's the case, yes it would be optimal to create it via the GHA of curatedMetagenomicData.
