### ISSUE TITLE
Why is combined_metadata renamed to sampleMetadata?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#196]
I think this should remain the same as before, `combined_metadata`. @schifferl was this an intentional change?

**Comment by lwaldron** [comment]
This is an unnecessary API change so shouldn't be made without the usual deprecation process (although I don't think it merits that either).

**Comment by schifferl** [comment]
Hi @lwaldron, this change was intentional to bring us closer to Bioconductor convention (i.e. camelCase) for user facing API methods and objects. I have approved pull request #211, but if there are not objections, I think we might close it and avoid the trouble of resolving conflicts. We can add a deprecated `combined_metadata` object that is a copy of `sampleMetadata` and offer a message about switching to maintain some backwards compatibility, if necessary.
