### ISSUE TITLE
Restore functionality of legacy curatedMetagenomicData

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#199]
* One dataset: curatedMetagenomicDataSet()  # returns a SummarizedExperiment
* Multiple datasets: curatedMetagenomicData()  # returns a list of outputs from curatedMetagenomicDataSet

**Comment by schifferl** [comment]
I would like to stick with the `sapply` approach rather than implement two functions that do mostly the same thing. Yes, users would have to change their code by adding one `sapply` line and things would break; but, it would let them know about the API change.

To demonstrate, consider a cMD 1 user with this code:
```r
curatedMetagenomicData("AsnicarF_20*.relative_abundance", dryrun = FALSE)
```

To update to the current cMD 3 API this code would become:
```r
curatedMetagenomicData("AsnicarF_20.+.relative_abundance", dryrun = TRUE) |>
    sapply(curatedMetagenomicData, dryrun = FALSE)
```

Or for someone who insisted on keeping things the old way, the following:
```r
curatedMetagenomicData <- function(x, ...) {
    utils::glob2rx(x) |>
        curatedMetagenomicData::curatedMetagenomicData(...) |>
        base::sapply(curatedMetagenomicData, dryrun = FALSE)
}
```

I am willing to keep the discussion going, but feel pretty strongly about steering users towards the new API method as it's implemented now for a few reasons: 1) the API didn't change much in its arguments (they are mostly the same) or nature (data is still returned), and 2) because we made a branch and v 1.20.0 should remain installable for the foreseeable future. Anyone really wanting things to stay the same can have it that way (and they probably want the old data anyway) but the v 3.0.0 profiles come at the cost of switching to the new API (albeit a small one).

**Comment by lwaldron** [comment]
Alright, I don't feel as strongly about it, let's keep it as-is with documentation in the vignette (#65) for what to replace a cMD 1 call with in cMD 3.
