### ISSUE TITLE
Restore check-bioc.yml

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/curatedMetagenomicData#203]
Get https://github.com/waldronlab/curatedMetagenomicData/blob/46852cae6cf21324b9104e39f8cd820f970ac455/.github/workflows/check-bioc.yml to test on different OSes. It will also create a pkgdown site so we can remove https://github.com/waldronlab/curatedMetagenomicData/blob/master/.github/workflows/pkgdown.yaml.

`git restore --source 46852 -- .github/workflows/check-bioc.yml` will get the file from a previous commit history.

**Comment by lwaldron** [comment]
Sounds like a good plan to me.

**Comment by lwaldron** [comment]
I would say, go for it @jwokaty

**Comment by lwaldron** [comment]
One thing to think about - the pkgdown site and `combined_metadata` object only need to be built once, whereas it's great to run `R CMD CHECK` and `BiocCheck` on all platforms. I guess it doesn't hurt to do the other things three times, but there's no benefit to it since we're only interested the produced web page or rda file.

**Comment by jwokaty** [comment]
@lwaldron The pkgdown site will only be generated with the Linux runner. I think it's best to keep the action to update combined_metadata separate since we'll be using a cron job with it.

**Comment by lwaldron** [comment]
got it!
