### ISSUE TITLE
refactor GitHub actions

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicData#242]
Currently the GitHub actions do not accomplish their intended behavior and only display a red x next to each commit. They should be refactored to accomplish the following tasks:
1. knit the `README.Rmd` file into the `README.md` file
2. update the documentation with `devtools::document()` if needed
3. check the package (`devtools::check(args = c('--no-vignettes','--timings'), build_args = c('--keep-empty-dirs','--no-resave-data'))`)
4. run `BiocCheck::BiocCheck()`
5. build the pkgdown website

Also, the curation action has a few issues that need to be rectified:
1. it should create a pull request against both release (i.e. the `RELEASE_3_13` branch) and devel (i.e. the `master` branch)
2. the devel pull request should not create the `combined_metadata` object

The alternative would be to remove these actions and I can take care of the tasks on my own machine. Just let me know if that's a better approach.

**Comment by jwokaty** [comment]
@schifferl When `knit` and `devtools::document()` creates a commit, can the action create PR so that you can review it? check-bioc.yml can build the pkgdown site so I think we can remove https://github.com/waldronlab/curatedMetagenomicData/blob/master/.github/workflows/rmarkdown.yaml. It's also running `BiocCheck::BiocCheck()` and running `rcmdcheck`, but I can replace it with the code in 3 from above. .
