### ISSUE TITLE
add NCBI taxonomy IDs to the rowData

### ISSUE THREAD

**Issue by lgeistlinger** [waldronlab/curatedMetagenomicData#245]
**Is your feature request related to a problem? Please describe.**
cMD 3.0 serves TreeSummarizedExperiments based on Metaphlan clade names. For integration purposes with other data resources such as microbe signatures from BugSigDB, it is typically helpful to have them mapped to NCBI taxonomy IDs. 

**Describe the solution you'd like**
A convenient solution from a user's perspective would be to have a column in the rowData that stores the NCBI taxonomy ID for each species. That is very similar to what we eg have in curatedOvarianData where datasets are based on gene symbols but mapping to NCBI Entrez Gene IDs is available in the fData of each dataset. 

**Describe alternatives you've considered**
There are arguments to leave annotation  to the user. One could just point the user to the corresponding metaphlan mapping file or packages for ID conversion such as taxize. Especially less experienced users will however appreciate a way to easily map without taking those steps. 

**Additional context**
Happy to help with this + can provide code / pull request if pointed to the place where the TreeSummarizedExperiments are assembled and additional annotations can be made.

**Comment by schifferl** [comment]
Thanks @lgeistlinger! I think you are right, there is no reason to leave annotation to the user. Let's get it fixed by adding the mapping file from metaphlan – do you know where it is? Or do we need to create mapping annotations using taxize? Either way, could you take a look at `data-raw/sysdata.R` and add some lines there to read and save the file as an R object? Go ahead and to commit directly to master, then when you're done I will add the annotations to the constructor.

**Comment by lgeistlinger** [comment]
Yes we have metaphlan2.0 and metaphlan3.0 mapping files from Francesco, let me dig them up and take a look at `data-raw/sysdata.R`. Will report back.

**Comment by fbeghini** [comment]
Here's the NCBI taxid --> taxonomy map. This consider only the NCBI taxonomy ID of the species, let me know if you want the full taxonomy with the IDs for all the ranks
[mpa_v30_taxonomy.txt](https://github.com/waldronlab/curatedMetagenomicData/files/6649324/mpa_v30_taxonomy.txt)

**Comment by lgeistlinger** [comment]
Thanks Francesco, yep the full file would be helpful as I currently think that we want to mirror the existing rowData columns 

```
> se <- curatedMetagenomicData("AsnicarF_2017.relative_abundance", dryrun = FALSE)
> colnames(rowData(se[[1]]))
[1] "Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species"
```

storing taxonomic names for each taxonomic rank with the corresponding NCBI IDs for each taxonomic rank.

**Comment by lgeistlinger** [comment]
I have this file - so if this hasn't changed I have everything I need, Francesco: https://github.com/seandavi/MungeCuratedMGS/blob/master/inst/extdata/mpa_v30_CHOCOPhlAn_201901_taxonomy.txt.gz

**Comment by lwaldron** [comment]
```
> se <- curatedMetagenomicData("AsnicarF_2017.relative_abundance", dryrun = FALSE)
> colnames(rowData(se[[1]]))
[1] "Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species"
```
Note though that AFAIK cMD 3.0 only has rows corresponding to species, so the other columns refer only to ancestors and not to the species in the row itself (in other words, species is never missing, it is always the terminal node).

**Comment by lgeistlinger** [comment]
I think you do, having aggregation operations like those implemented by `mia::splitByRanks` in mind. You'd like to eg easily aggregate species counts to genus level, and intersect genus level NCBI IDs for the genus level with other data sources of interest (such as genus level signatures from BugSigDB using NCBI IDs).

**Comment by schifferl** [comment]
Just checked checked back in here and will add a bit of clarification. Yes, only the species level clades remain in the object that is served to users. This would mean we could just do those mappings and depend on aggregate by rank to do the right thing as it moved up the taxonomy. (We should check that it modifies rowData as needed). Otherwise, we would need all levels (Class, Order, etc.) as stated by @lgeistlinger. If the files are handy, just import both and then we can check the behavior of aggregate by rank.

**Comment by lgeistlinger** [comment]
Hi. Just coming back to this. @schifferl: if I understand you correctly you just want to add 

```
map.df <- readr::read_tsv("https://raw.githubusercontent.com/seandavi/MungeCuratedMGS/master/inst/extdata/mpa_v30_CHOCOPhlAn_201901_taxonomy.txt.gz", col_names = c("metaphlan", "ncbi"), col_types = "cc")
```

to `data-raw/sysdata.R` and take it on yourself from there. Any other input from my side needed?

Take a look at:

```
> head(map.df)
# A tibble: 6 x 2
  metaphlan                                            ncbi                     
  <chr>                                                <chr>                    
1 k__Bacteria|p__Proteobacteria|c__Deltaproteobacteri… 2|1224|28221||||1797814  
2 k__Bacteria|p__Proteobacteria|c__Alphaproteobacteri… 2|1224|28211|204458|7689…
3 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacill… 2|1239|91061|186826|3395…
4 k__Bacteria|p__Proteobacteria|c__Alphaproteobacteri… 2|1224|28211|204457|4129…
5 k__Viruses|p__Viruses_unclassified|c__Viruses_uncla… 10239|||28883|10699|1299…
6 k__Bacteria|p__Actinobacteria|c__Actinobacteria|o__… 2|201174|1760|85007|1762…
```

My idea would have been to extract rank-level mapping from and and then map the existing cMD rowData columns (storing taxonomic names at each rank for each of the rows/species included in the dataset).

Not sure whether the mapping in the file is complete for all levels (but we could supplement that) and whether MungeCuratedMGS is really the right repo for hosting and pulling this file from (I had hoped for a central metaphlan data repo hosting this file @fbeghini).

**Comment by schifferl** [comment]
After some discussion at the coordination meeting, this feature will be added by providing an additional argument to the `curatedMetagenomicData` method as follows.

Current:
```r
curatedMetagenomicData(pattern, dryrun = TRUE, counts = FALSE)
```
Future:
```r
curatedMetagenomicData(pattern, dryrun = TRUE, counts = FALSE, rownames = c("long", "short", "NCBI")
```

The rownames (long, short, and NCBI) will come from the MetaPhlAn tree [file](https://github.com/biobakery/MetaPhlAn/blob/master/metaphlan/utils/mpa_v30_CHOCOPhlAn_201901_species_tree.nwk), which will be parsed into a mapping file (probably a `data.frame`). This design will allow users to choose rownames to suit their needs and will not interfere with `mia:: splitByRanks` or the command line interface. If there are any objections (@lgeistlinger, since you've asked for the feature), let me know; otherwise, I'll move ahead with the stated implementation shortly.

**Comment by lgeistlinger** [comment]
It sounds great. I'll be interested to see how `mia::splitByRanks` will work out, when choosing NCBI Ids as rownames. AFAIK that means for a species-level CMD dataset, that you will also need to have the NCBI IDs for the other ranks in the rowData (?) in order to get a genus-level dataset on NCBI IDs from `altExps`.

**Comment by schifferl** [comment]
Hmm, this is a good point... Even with `rownames = "NCBI"` I guess the row name would come out as the `"short"` taxonomic clade (e.g. Bacteroidetes)  when running `mia:: splitByRanks` and then need to be mapped again. (The elements of the `rowData` table are always the names of clades in my scenario; only the row names change per the `rownames` argument). I would have to test this, but if it is the case, it would be better to provide users with a method to map the row names (as many times as needed). The method could then be integrated into the `curatedMetagenomicData` method or used independently. I'll experiment and report back.

**Comment by schifferl** [comment]
@lgeistlinger this feature now exist in the `rownames` branch and is ready to be tried out. The implementation is as described above. For example to get the NCBI taxonomy IDs as the rownames for the `AsnicarF_2017` `relative_abundance` data set, do the folllowing:
```r
curatedMetagenomicData("AsnicarF_2017.relative_abundance", dryrun = FALSE, rownames = "NCBI")
```
The other choices for the `rownames` argument are `"long"` (the default) and `"short"` (the species name). Just needs to be tried out (@lgeistlinger) and documented/unit-tested (@schifferl) before merging into main.

FYI @lwaldron and @fbeghini too, since you were members of the converstation.

Also, this exposed what I think is a bug in `TreeSummarizedExperiment` because changing the `rownames` was not a simple `rownames() <-` and rather required the following.

```r
base::rownames(tree_summarized_experiment) <-
    new_names

base::rownames(tree_summarized_experiment@rowLinks) <-
    new_names
```

If not fixed in `TreeSummarizedExperiment` it will make it difficult for users to update the `rownames` of any `relative_abundance` data type.

Finally, as to the previous comment – `mia::splitByRanks` still works as expected with `rownames = "NCBI"`. The list of experiments returned changes the rownames to taxa and that seems like the correct behavior. If users wanted to map those to NCBI taxonomy, they would have to do so on their own using `taxize`. It's not such a big ask though because the `rowData` already contains the valid taxonomic names from NCBI (i.e. I didn't just split the names from the taxonomic tree; I mapped the entire hierarchy down the species-level). Anyway, please try this out and report back.

**Comment by lgeistlinger** [comment]
Maybe only my perspective, but it seems as if we are stopping halfway and end up a bit in a mixed state. I'd think it would be cool / very useful if somebody decides s/he likes to work on NCBI IDs that agglomeration options downstream would consistently return NCBI IDs too. For that to work, taxonomy rank columns in the rowData would need to be the corresponding NCBI IDs too. If the argument is users can use taxize for ID mapping, then there seems to be no rationale for including an option to return NCBI rownames. What do you think?

**Comment by lwaldron** [comment]
I’ll add that taxonomy names are a bit analogous to gene symbols, and NCBI
IDs are more analogous to Entrez IDs. Species names can change or be
re-assigned to other parts of the taxonomy, but IDs are much more stable.
These particular IDs are valuable _if_ they are taken from MetaPhlAn
output, because they guarantee knowing exactly what was meant by that name.
If you look up names with taxize, there is no such future guarantee. So
it’s valuable to maintain the NCBI IDs from the MetaPhlAn data files
_somewhere_, but less valuable to provide taxize IDs.

The MetaPhlAn  output provides only species IDs, but looking up the rest of
the taxonomy from those IDs should be reliable. I tend to agree that if
rownames are IDs, it may be surprising / undesirable for those using them
to see reversion to (potentially aliased, moved, outdated) names after
splitByRank, and full use of IDs would be more consistent. But that’s only
an inconvenience, not providing the original MetaPhlAn NCBI IDs anywhere in
the package is information loss that could necessitate future sleuthing to
recover. (sub-note, I guess this must not be a huge deal though, since
previous versions of MetaPhlAn didn’t include NCBI IDs in the data files).
-- 

--

Levi Waldron

Associate Professor

Department of Epidemiology and Biostatistics

CUNY Graduate School of Public Health and Health Policy

Institute for Implementation Science in Population Health

55 W 125th St, New York NY 10035

https://waldronlab.io

Join the microbiome Virtual International Forum: https://microbiome-vif.org

**Comment by schifferl** [comment]
Just to be _extra_ clear, this is the way `rowData` is currently returned per the implementation, given `rownames` argument.

---

`rownames = "long"`
|                                 | superkingdom | ... | species                    |
|---------------------------------|--------------|-----|----------------------------|
| k__Bacteria\|p__Spirochaetes... | Bacteria     | ... | Treponema lecithinolyticum |
| ...                             | ...          | ... | ...                        |
| k__Bacteria\|p__Spirochaetes... | Bacteria     | ... | Treponema bryantii         |

---

`rownames = "short"`
|                            | superkingdom | ... | species                    |
|----------------------------|--------------|-----|----------------------------|
| Treponema lecithinolyticum | Bacteria     | ... | Treponema lecithinolyticum |
| ...                        | ...          | ... | ...                        |
| Treponema bryantii         | Bacteria     | ... | Treponema bryantii         |

---

`rownames = "NCBI"`
|       | superkingdom | ... | species                    |
|-------|--------------|-----|----------------------------|
| 53418 | Bacteria     | ... | Treponema lecithinolyticum |
| ...   | ...          | ... | ...                        |
| 163   | Bacteria     | ... | Treponema bryantii         |

---

The suggestion is that for `rownames = "NCBI"` the `rowData` should look like this instead.

`rownames = "NCBI"`
|       | superkingdom | ... | species |
|-------|--------------|-----|---------|
| 53418 | 2            | ... | 53418   |
| ...   | ...          | ... | ...     |
| 163   | 2            | ... | 163     |

I don't know that I'm convinced of this design yet, and it doesn't really coincide with the `rownames` argument to be certain. To achieve the desired result without completely removing the clade names from the `rowData`, a `data.frame` of mappings could be exposed to users. In my mind, it would look like this:

| txid  | level        | name                       |
|-------|--------------|----------------------------|
| 2     | superkingdom | Bacteria                   |
| 163   | species      | Treponema bryantii         |
| 53418 | species      | Treponema lecithinolyticum |

This `data.frame` would come from @fbeghini's mappings above:

> Here's the NCBI taxid --> taxonomy map. This consider only the NCBI taxonomy ID of the species, let me know if you want the full taxonomy with the IDs for all the ranks
> [mpa_v30_taxonomy.txt](https://github.com/waldronlab/curatedMetagenomicData/files/6649324/mpa_v30_taxonomy.txt)

Just that I wonder about the provenance of this file and think the [MetaPhlAn](https://github.com/biobakery/MetaPhlAn) repo might be a better place for it, so it's maintained long-term and we don't receive issues that our taxonomy is out of date. If it were there, I would just download and process it into the mapping `data.frame`, which would be used to provide the `rowData` per the current implementation and allow users to do mappings of their own after `mia::splitByRanks`.

If the file is there, like the phylogenetic tree is, most of the programming is already done and we can do updates easily in the future.

**Comment by lgeistlinger** [comment]
> The suggestion is that for rownames = "NCBI" the rowData should look like this instead.

Exactly. I am noting that there would be alternatives to completely stripping off the clade names from the `rowData`, and rather just add ".NCBI" columns such as "species.NCBI", "genus.NCBI". Those ".NCBI" columns could then be registered by modifying `taxonomyRanks` of the TreeSE when `rownames = NCBI` is chosen. 

> Just that I wonder about the provenance of this file and think the MetaPhlAn repo might be a better place for it, so it's maintained long-term and we don't receive issues that our taxonomy is out of date

Fully with you on this one.

**Comment by lgeistlinger** [comment]
I couldn't believe that the NCBI taxonomy hasn't been wrapped in one way or another into Bioconductor annotation resources. After a bit of search, I think mapping from [GenomeInfoDbData](https://bioconductor.org/packages/GenomeInfoDbData) comes close to what we are looking for.

```
library(GenomeInfoDbData)
data(specData)
> head(specData)
  tax_id        genus     species
1      1          all        <NA>
2      1         root        <NA>
3      2     Bacteria        <NA>
4      6 Azorhizobium        <NA>
5      7 Azorhizobium caulinodans
6      9     Buchnera  aphidicola
> dim(specData)
[1] 2521271       3
> subset(specData, c(genus == "Escherichia" & species ==" coli"))$tax_id
[1] 562
```

They only include genus and species in a somewhat simplified/incorrect way in that table (eg bacteria = genus), but there is a 
[script](https://github.com/Bioconductor/GenomeInfoDbData/blob/master/inst/scripts/updateGenomeInfoDbData.R) that extracts this table from the full dump of the NCBI Taxonomy, that we could extend via a pull request to pull out also the other taxonomic ranks. Do we think that this is worth a try, or are we better off having a file laying around somewhere? My hope with a Bioconductor annotation package such as `GenomeInfoDbData` would be that it comes with provenance and regular updates that we need.

**Comment by lwaldron** [comment]
That sounds like a great idea @lgeistlinger, having the full and correct NCBI taxonomy seems like an obvious omission and correcting it would have value for us and others. I'll post a question on bioc-devel about whether to update or add.

**Comment by nsegata** [comment]
Hi all, just chiming in because while in MetaPhlAn 2 we provide in the
output only the species-level NCBI IDs, we do have all the internal IDs and
in MetaPhlAn version >2 we report them as well in the output. For MetaPhlAn
2 we can provide all the IDs. Because of the problems Ludwig was observing
in the NCBI hierarchical taxonomy, in all MetaPhlAn versions we edited the
taxonomy to derive a hierarchy with a fixed number of levels (from phyla
p__ to species s__) and to fill in the missing ones. Having a fixed number
of levels is important otherwise when summing up abundances at levels
higher than the species it becomes difficult to interpret. I would thus
suggest getting all the NCBI taxonomy from MetaPhlAn, it is going to be
super easy for version >2 (and doable for version 2)
Nicola

**Comment by lwaldron** [comment]
Thanks @nsegata! I agree that for curatedMetagenomicData, this cleanup indicates we should be using a map from MetaPhlAn. Would you mind publicly posting this file along with versions indicating which versions of MetaPhlAn it should be used with?

@lgeistlinger having the full NCBI taxonomy in Bioconductor may still be useful for bugsigdb, which is full of modifiers that aren't relevant for MetaPhlAn ("Unclassified" genera and family, sp., species missing a genus, etc).

**Comment by nsegata** [comment]
Sure, @Francesco Beghini ***@***.***> and @Aitor Blanco
***@***.***> should have the whole taxonomic tree to
provide for MetaPhlAn 3 and >3 respectively. For MetaPhlAn 2 maybe @Paolo
Manghi ***@***.***> or @***@***.***
***@***.***> can locate it?

**Comment by lwaldron** [comment]
@fbeghini @paolinomanghi see above, I think your handles got munged.

**Comment by schifferl** [comment]
Thank you all for all the comments, it's pretty clear on my end how to handle this now. If @fbeghini puts the `mpa_v30_taxonomy.txt` file into the MetaPhlAn repo, I can take it from there and get this finished.

And just to clarify on @lgeistlinger's comment about annotation resources:

>Do we think that this is worth a try, or are we better off having a file laying around somewhere? My hope with a Bioconductor annotation package such as GenomeInfoDbData would be that it comes with provenance and regular updates that we need.

Both, because I want the exact mapping from MetaPhlAn and something to check them against too.

**Comment by schifferl** [comment]
Sorry, one more comment. We can keep that file, `mpa_v30_taxonomy.txt`, in our repo if we really need too. Just that @fbeghini (or someone else who knows how to update it) would have to maintain it for us.

**Comment by fbeghini** [comment]
> Sorry, one more comment. We can keep that file, `mpa_v30_taxonomy.txt`, in our repo if we really need too. Just that @fbeghini (or someone else who knows how to update it) would have to maintain it for us.

@schifferl, no problem, there should not be any updates for this release, so the IDs will not change. The file can be easily generated by loading the pkl file and inspecting the `['taxonomy']` field.

**Comment by lgeistlinger** [comment]
> Both, because I want the exact mapping from MetaPhlAn and something to check them against too.

Hi @schifferl: I agree that the metaphlan3 file from Franceso is the reference point (likely with edge cases resolved), but here is a [script](https://www.dropbox.com/s/gwaman1miz1dvv9/metaphlan3ncbi.R?dl=0) that maps metaphlan3 taxonomic clades to NCBI taxonomy IDs and returns a 3-column data.frame (txid, level, name) as per [your specification](https://github.com/waldronlab/curatedMetagenomicData/issues/245#issuecomment-891897746). Can pull request if that's convenient, but you might want to work it into the repo in a way that you see fit best. Hope that helps.

**Comment by lwaldron** [comment]
Awesome @schiffer!!

**Comment by fbeghini** [comment]
> If you notice any issues, just let me know; otherwise, I'll close the issue in the next day or so. If you care about the specifics of the implementation, you can study the files in the [`data-raw`](https://github.com/waldronlab/curatedMetagenomicData/tree/master/data-raw) directory. Finally, the feature brought to my attention one other change I'd like to suggest for MetaPhlAn3: the Newick tree [file](https://github.com/biobakery/MetaPhlAn/blob/master/metaphlan/utils/mpa_v30_CHOCOPhlAn_201901_species_tree.nwk) should be stored with the other CHOCOPhlAn files on [Zenodo](https://doi.org/10.5281/zenodo.3955744). Essentially, I'd like the second line of [phylogeneticTree.R](https://github.com/waldronlab/curatedMetagenomicData/blob/master/data-raw/phylogeneticTree.R) and [rowData.R](https://github.com/waldronlab/curatedMetagenomicData/blob/master/data-raw/rowData.R) coming from the same place, just for consistency. Let me know if that's possible @fbeghini and I'll make the changes to cMD once it's done. Anyway, hope you're all happy with the feature and let me know if there's anything else.

@schifferl  I updated the Zenodo record with the Newick tree, here's the new link https://zenodo.org/record/5668382

**Comment by schiffer** [comment]
body {	
          font-family: sans-serif, Arial, Verdana, "Trebuchet MS";
          font-size: 10pt;
          color: #333;	
          background-color: #fff;
          margin: 5px; 
          }
          
          .origmessagetext_quote {border-left:2px solid #ccc;  }
 blockquote { margin-top: 0; padding-left: 5px;  margin-left: 2px; }
 
          
I suppose that I got this message by mistake.

Best regards,
J.Schiffer

----- Ursprüngliche Nachricht -----
Von: Francesco Beghini ***@***.***>
Datum: 10.11.2021 17:20
An: waldronlab/curatedMetagenomicData ***@***.***>
Kopie: schiffer ***@***.***>, Mention ***@***.***>
Betreff: Re: [waldronlab/curatedMetagenomicData] add NCBI taxonomy IDs to the rowData (#245)
 


 


If you notice any issues, just let me know; otherwise, I'll close the issue in the next day or so. If you care about the specifics of the implementation, you can study the files in the data-raw directory. Finally, the feature brought to my attention one other change I'd like to suggest for MetaPhlAn3: the Newick tree file should be stored with the other CHOCOPhlAn files on Zenodo. Essentially, I'd like the second line of phylogeneticTree.R and rowData.R coming from the same place, just for consistency. Let me know if that's possible @fbeghini and I'll make the changes to cMD once it's done. Anyway, hope you're all happy with the feature and let me know if there's anything else.


@schifferl I updated the Zenodo record with the Newick tree, here's the new link https://zenodo.org/record/5668382

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
