### ISSUE TITLE
About QC procedure contained in pipeline 

### ISSUE THREAD

**Issue by luzhang321** [waldronlab/curatedMetagenomicData#257]
Hi :) 

Sorry to bother you again. 
In order to understand the pipeline you used in cMD packageand directly use the output from cMD package, I read the nf file used in the package : https://github.com/seandavi/curatedMetagenomicsNextflow/blob/main/main.nf 

I checked through the qc procedure and find that a qc report and reads count will be produced after using `fasterq-dump` to download the reads. 
But other qc procedures like adapter, primers removing or human/host reads removing are NOT contained. [if I didn't find it, please feel free to tell me]. Will that affect the quality of results? 
I am curious that why these kinds of procedures are not contained? Is that because the reads [download from ncbi-sra] are very neat? 
Or is that because as default the human reads will not be very high, so not removing the host reads won't affect a lot? 

Thanks very much! 
Best Regards,
Lu

**Comment by schifferl** [comment]
Hi @luzhang321, I have looked at the Nextflow [pipeline](https://github.com/seandavi/curatedMetagenomicsNextflow) too and noticed there are not QC steps. I think this is likely because submission to SRA involves these steps and removal of human reads done by NCBI, but I don't maintain that part of the project so it's difficult for me to say for sure. Anyway, the R/Bioconductor software repository is not the best place to discuss these issues, please open issues with the Nextflow [pipeline](https://github.com/seandavi/curatedMetagenomicsNextflow) if you need to discuss it further, and as per the [contributing guidelines](https://github.com/waldronlab/curatedMetagenomicData/blob/f9d91705d8134bbc5202d0977b91c8ca8cb5dd74/CONTRIBUTING.md) please seek user support through the Bioconductor support site (https://support.bioconductor.org/) in the future.
