### ISSUE TITLE
Output format for the data download

### ISSUE THREAD

**Issue by antagomir** [waldronlab/curatedMetagenomicData#296]
**Is your feature request related to a problem? Please describe.**

Downstream analyses could benefit from organizing the downloaded taxonomic and functional profiles into a standard data container instead of a list when this is possible.

**Describe the solution you'd like**

Instead of a list of (Tree)SE objects, the curatedMetagenomicData could return a MultiAssayExperiment object, or use altExp slots to combine the interlinked taxonomic profiles and functional predictions. This could be provided an option that the user can choose for the returned output data format, even if this is not applicable to all downloads combinations in general.

**Describe alternatives you've considered**

At the moment, the individual (Tree)SE objects can be combined manually into a single (Tree)SE or MAE after the download.

**Comment by lwaldron** [comment]
Using the `altExp` slots for multiple data types of the same dataset would be reasonable, and would also avoid situations like #295. `altExp` seems preferable to `MultiAssayExperiment` in this case because it's the simplest representation that the data can fit into.

However since this would be an API-breaking change, it should either go through a deprecation cycle or be added as optional functionality.  I think I would be more inclined to add a helper function or documentation of how to do this rather than breaking the existing API, but open to comments about how an API change would benefit downstream analysis.

**Comment by antagomir** [comment]
The benefit from adding it directly to the function (API) is that the extra step of creating the altExps can be avoided and this would simplify data retrieval. If it could be added as an optional functionality, the API should still work for the current use cases. If this is not feasible to implement, then a helper function (or documentation) could be handy.

**Comment by schifferl** [comment]
I think this feature is too specific for curatedMetagenomicData and will not be added. 

Feel free to implement a DIY solution, but the package will remain broadly focused.
