### ISSUE TITLE
data object for combined metadata

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#38]
Call it `data/subjectdata.rda` (save with high compression), also need `man/subjectdata.Rd` file. Needed for issues #10 and #30. 

Make a note of this `data.frame` in the vignette.

**Comment by schifferl** [comment]
Would this perhaps be a good place to use an internal `sysdata.rda` file (http://r-pkgs.had.co.nz/data.html#data-sysdata)?

**Comment by schifferl** [comment]
close by 0a583f4

**Comment by lwaldron** [comment]
[0a583f4](https://github.com/waldronlab/curatedMetagenomicData/commit/0a583f411a7f6eb2a49a87c5566227e463e4fa89) titled "changes to template.csv to make some variables numeric" seems to be unrelated to this issue? 

Aha, I think it's [c506f74](https://github.com/waldronlab/curatedMetagenomicData/commit/c506f74a4a3fa22e7856bfab07ea7d06855346ea). But two questions:

1. How does a user load this object? If it is exported and documented (and usually in data/, not R/), they can do data(combined_metadata)
2. Should there be a column saying which study the row is from?

**Comment by lwaldron** [comment]
Ah, I just saw that you had proposed this as an internal, hidden data file. What's the justification? I would think the participant metadata would be of potential use to the user, but you might be able to convince me otherwise with good reason...

**Comment by schifferl** [comment]
Oops, it is c506f74 and there should be a row with the study name. I will be very difficult to find the data otherwise.

As for why we might prefer an internal data file, I see the curatedMetagenomicData function as the main interface for the package and not the `data.frame` itself. If we use the function to download a dataset we can then pass that on programmatically to something else. In essence, every user will want to download some data from the package and by using an internal file with curatedMetagenomicData function the process will be consistent. Also, the function should help us as we develop the Shiny app.

I can document and export the file if you think it is better that way but it just seems the cMD function and your CLI interface are a better way to interact with the data.

**Comment by lwaldron** [comment]
Users certainly should be required to interact with the metadata table, but here are a couple use cases for it I can think of:

1. user does an analysis spanning thousands of samples, but wants to make a descriptives table in a script without having to load all those datasets

2. user would like to count the number of certain types of samples available to see if analysis is worthwhile, before doing download

3. user would just like to open up the metadata in a spreadsheet or View() just to "see" what's  available. I've felt this way sometimes about TCGA metadata.

4. advanced user would like to do some sample selection methodology not supported by the `curatedMetagenomicData()` function.

And I don't see much downside, do you?

**Comment by schifferl** [comment]
No downside to it. I will export and document the file and then it can be used both internally and externally.

**Comment by schifferl** [comment]
The combined metadata is not exported yet but it is corrected to include the `dataset_name`. Will have it exported shortly but just wanted to mention that it's available now : )

**Comment by schifferl** [comment]
After a bit of a struggle with automated documentation, this issue is closed by a664c26.
