### ISSUE TITLE
Searching by metadata

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#6]
@vobencha, can we put the metadata that are currently in `experimentData(obj)` into the `mcols(x)` where `x` is the ExperimentHub query, to make them searchable without downloading the datasets? 

I originally thought it might belong in `mcols(myquery)$description`, but in the [ExperimentHubMetadata class definition](https://github.com/Bioconductor-mirror/ExperimentHubData/blob/master/R/ExperimentHubMetadata-class.R) I see this is class "NA_character_". How about an additional metadata slot of class ANY where we could just put a list containing the `pData` and `experimentData`?  It would also be nice to be able to search some of the values from `pData(obj)`, like "bodysite".

**Comment by vobencha** [comment]
Yes, we can make the data in experimentData(obj) available for searching and I would do this by putting in it the 'description' field. I don't think it would be useful to add a slot of class ANY because the metadata are stored in a mysql db where the concept of a list doesn't really exist. To make fields searchable we can either store fields separately or as a single character string with a delimiter separating multiple fields.

* store fields separately
Key search terms such as bodysite or study could be added to the 'tags' field. curatedMetagenomicData could have a helper that listed all possible bodysites and/or studies so users know what the available search terms are. Of course the terms would also be discoverable via tags(x) but it might not be obvious that 'Candela_Africa' is the name of a study; having a helper that listed the possible studies might be nice.

* store multiple fields as character field
The 'description' field is TEXT so it's large enough to hold the information in experimentData() but it would not be well formatted in a show() method and, without further parsing, would just appear as a long character string. When query(ehub, ...) is invoked, all metadata fields are searched via grep so even if 'description' is a long semi-colon separated string, the individual terms can be found without parsing. I think pData() is too large to be considered metadata in this case.

My recommendation would be to decide on a few key search terms and include those in the 'tags' field. Too many terms or too much metadata can be overwhelming. Give the user a roadmap of how to navigate through the data, i.e., 'search on bodysite and/or study and here are your options ...'. If you want a more verbose 'description' we can certainly do that. I just wouldn't rely on the user to read through the 'description' (or other lengthy) field to identify search terms.

FYI, it looks like we have an (unintentional?) error in several objects under 'platform_summary':
> xx = experimentData(Candela_Africa.stool.pathCov.eset)
> xx
Experiment data
  Experimenter name: Rampelli S, Schnorr SL, Consolandi C, Turroni S, Severgnini M, Peano C, Brigidi P, Crittenden AN, Henry AG, Candela M 
  Laboratory: Department of Pharmacy and Biotechnology, University of Bologna, Bologna 40126, Italy. 
  Contact information:  
  Title: Metagenome Sequencing of the Hadza Hunter-Gatherer Gut Microbiota 
  URL:  
  PMIDs: 25981789 
  Abstract: A 213 word abstract is available. Use 'abstract' method.
  notes:
   platform_summary:Error in if (nchar(x[i]) > width) { : 
  missing value where TRUE/FALSE needed

Val

**Comment by lwaldron** [comment]
@schifferl , will you add the metadata fields that we discussed (I believe to metadata.csv) so that users will be able to sort and search by body site, data type, disease type?

**Comment by schifferl** [comment]
@lwaldron & @vobencha, I will add the the metadata with the rebuilding of the package from the raw data. They will be added to the `metadata.csv` file, but it makes the most sense to generate the file with the `make-metadata.R` script, as specified in the ExperimentHubData vignette. I will also provide helpers to give the names of searchable fields. The platform_summary error will also be resolved with the rebuild : )

**Comment by lwaldron** [comment]
Since the Experiment_Data.txt.bz2 and Pheno_Data.txt.bz2 end up in the ExpressionSet objects, would it be more simple and less error-prone to generate metadata.csv using the ExpressionSet objects themselves? Or in any case, using files that Edoardo has put in the metadata folder on iRODS.

**Comment by schifferl** [comment]
Exactly, I had it in mind to generate the `metadata.csv` file from the final `ExpressionSet` objects. That way we would not have any differences between the file and the actual objects.

**Comment by lwaldron** [comment]
I think this is addressed by the tags - Lucas, can you close after explaining how to select datasets by tags in the vignette?

**Comment by lwaldron** [comment]
duplicate of #30 which is a better solution.
