### ISSUE TITLE
unnecessary depends / imports / suggests?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicData#63]
I am not sure why some of these packages are depends / imports / suggests:

Suggests:
BiocInstaller, BiocParallel, BiocCheck - why are these suggested?

Imports:
BiocInstaller

Depends:
magrittr - you explicitly import those functions used in our package functions, so is this needed as a Depends? It seems only to be so for some trivial usage in function examples.
phyloseq, dplyr - also seems like these should be Suggests or Imports, not Depends?

**Comment by schifferl** [comment]
I have been doing some restructuring of how the package works internally, and will be able to take these out shortly. BiocInstaller, BiocParallel, BiocCheck are suggested because they are used in processing of the raw data – BiocInstaller can be removed from imports with the internal refactoring. I just need a few minutes to test everything on the SPH server and then I can fix this issue.
