### ISSUE TITLE
Package requires R3.4?

### ISSUE THREAD

**Issue by karchern** [waldronlab/curatedMetagenomicData#93]

**Comment by lwaldron** [comment]
Not really, unless you can manage to install the current release or devel
version of ExperimentHub and AnnotationHub (corresponding to the version of
curatedMetagenomicData you're running.) If you don't use the stock bioc
release or devel you're likely to run into dependency hell....

On Jul 28, 2017 12:03, "karchern" <notifications@github.com> wrote:

Hey,
I'm struggling with getting the most recent version of
curatedMetagenomicData on my machine as it requires R 3.4. This is a bit of
a pain as the most recent R version obtainable using anaconda is 3.3.2.

Is there any way around this?

Thanks for clarification,
Nic

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/waldronlab/curatedMetagenomicData/issues/93>, or mute
the thread
